@Library('jenkinstools@master') _

import com.splunk.jenkins.DockerRequest;
import com.splunk.tool.plugin.docker.extension.BadDockerExitCode;

def dockerReq = new DockerRequest(steps,
                                  currentBuild,
                                  env,
                                  [imageName: "repo.splunk.com/splunk/products/splact",
                                   userId: "10777",
                                   repoName: "https://github.com/cloudfoundry-community/splunk-firehose-nozzle.git",
                                   runner: "yarn",
                                   remotePath: "/build"])


withSplunkWrapNode("master") {
    try {
        stage("run orca") {
            withCredentials([file(credentialsId: 'srv_releases_orca', variable: 'ORCA_CREDENTIALS')]) {
                sh "tar -ovxf $ORCA_CREDENTIALS";
                splunkPrepareAndCheckOut request: dockerReq,
                                         files: "${WORKSPACE}/.orca, ${WORKSPACE}/.ssh";
            }
            splunkRunScript request:dockerReq,
                            script:
                                """
                                   pip install splunk_orca==0.8.0 -i https://repo.splunk.com/artifactory/api/pypi/pypi-virtual/simple
                                   cd ci

                                   splunk_orca create --sc nozzle
                                """;
        }
    }
    catch (BadDockerExitCode e) {
        currentBuild.result = "FAILURE";
        echo "Exception Caught: ${e.getMessage()}";
        echo "Stack Trace: ${e.printStackTrace()}";
    }
    catch (Exception e) {
        currentBuild.result = "FAILURE";
        echo "Exception Caught: ${e.getMessage()}";
        echo "Stack Trace: ${e.printStackTrace()}";
    }
    finally {
        steps.cleanWs();
    }
}
